[package]
name = "playback-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.8.3"
aws-sdk-s3 = "1.100.0"
reqwest = "0.12.22"
serde = "1.0.219"
serde_json = "1.0.142"
thiserror = "2.0.12"
tokio = "1.47.1"
