// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Job {
    /// Unique identifier for the job.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
